import { useState } from 'react'
import './App.css'
import Header from "./Header"
import Nav from "./Nav"
import Resume from "./Resume"
import Article from "./Article"
import Insta from "./assets/instagram.png"
import DLSS from "./assets/dlss3.jpeg"
import Games from "./assets/games.jpeg"

import {
  createBrowserRouter,
  RouterProvider,
} from "react-router-dom"

const router = createBrowserRouter([
  {
    path: '/',
    element: <Resume/>,
  },
  {
    path: '/games',
    element: <Article title="Video Game Release Dates: The Biggest Games of October 2023" author="Kiriratanak Vong" date="October 16, 2023" image={Games} 
    contents={
    <div>
      The major game releases just don't stop coming this year. 
      We've gotten gems like Baldur's Gate 3, The Legend of Zelda: Tears of the Kingdom, and Final Fantasy XVI, just to name a few. 
      October sees a whole new wave of heavy-hitters hitting shelves, from Spider-Man 2 to Assassin's Creed Mirage to Super Mario Wonder. 
      This month a big one, friends. So whether you do your gaming on PS5, Xbox Series X|S, Nintendo Switch, and/or PC, you'll find something worth playing this month.
      <ul>October 2023 - Playstation Game Release Dates
        <li>Assassin's Creed Mirage - October 5</li>
        <li>Sonic Superstars - October 17</li>
        <li>Spiderman 2 - October 20</li>
        <li>Cities: Skylines 2 - October 24</li>
        <li>Metal Gear Solid Master Collection Vol 1 - October 24</li>
        <li>Alan Wake 2 - October 27</li>
      </ul>
    </div>
    }/>,
  },
  {
    path: '/hardware',
    element: <Article title="Hardware" author="Kiriratanak Vong" date="October 16, 2023" image={Insta} 
    contents="This is a test."/>,
  },
  {
    path: '/software',
    element: <Article title="NVIDIA DLSS 3 - A Revolution in Neural Graphics" author="Kiriratanak Vong" date="October 16, 2023" image={DLSS} 
    contents={
    <div>
      DLSS 3 is a revolutionary breakthrough in AI-powered graphics that massively boosts performance, while maintaining great image quality and responsiveness. 
      Building upon DLSS Super Resolution, DLSS 3 adds Optical Multi Frame Generation to generate entirely new frames, and integrates NVIDIA Reflex low latency technology for optimal responsiveness. 
      DLSS 3 is powered by the new fourth-generation Tensor Cores and Optical Flow Accelerator of the NVIDIA Ada Lovelace architecture, which powers GeForce RTX 40 Series graphics cards. 
      The DLSS Frame Generation convolutional autoencoder takes 4 inputs – current and prior game frames, an optical flow field generated by Ada’s Optical Flow Accelerator, and game engine data such as motion vectors and depth.
    </div>}/>,
  },
]);

function App() {
  const [count, setCount] = useState(0)

  return (
    <>
      <Header/>
      <Nav/>
      <RouterProvider router={router}/>
    </>
  )
}

export default App
